# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: symfind

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: symfind
    main: ./src
    binary: symfind
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: symfind
    ids:
      - symfind
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
